export const UK_CITIES = [
  "Nottingham",
  "London",
  "Birmingham",
  "Manchester",
  "Leicester",
  "Sheffield",
  "Leeds",
  "Bristol",
  "Liverpool",
  "Derby",
  "Coventry",
  "Bradford",
  "Newcastle upon Tyne",
  "Sunderland",
  "Hull",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Plymouth",
  "Southampton",
  "Reading",
  "Luton",
  "Northampton",
  "Milton Keynes",
  "Swindon",
  "Peterborough",
  "Cambridge",
  "Oxford",
  "York",
  "Gloucester",
  "Exeter",
  "Cardiff",
  "Swansea",
  "Edinburgh",
  "Glasgow",
  "Aberdeen",
  "Dundee",
  "Belfast",
] as const;

export type UkCity = (typeof UK_CITIES)[number];

export const UK_DISTRICTS_BY_CITY: Record<UkCity, readonly string[]> = {
  Nottingham: [
    "City Centre",
    "Arnold",
    "Beeston",
    "Bulwell",
    "Carlton",
    "Clifton",
    "Hucknall",
    "Mapperley",
    "Radford",
    "Sherwood",
    "St Ann's",
    "West Bridgford",
    "Wollaton",
  ],
  London: [
    "Westminster",
    "Camden",
    "Islington",
    "Hackney",
    "Tower Hamlets",
    "Greenwich",
    "Lewisham",
    "Southwark",
    "Lambeth",
    "Wandsworth",
    "Hammersmith and Fulham",
    "Kensington and Chelsea",
    "Haringey",
    "Enfield",
    "Barnet",
    "Brent",
    "Ealing",
    "Hounslow",
    "Croydon",
    "Bromley",
  ],
  Birmingham: [
    "City Centre",
    "Edgbaston",
    "Erdington",
    "Hall Green",
    "Handsworth",
    "Kings Heath",
    "Moseley",
    "Northfield",
    "Selly Oak",
    "Sutton Coldfield",
    "Yardley",
  ],
  Manchester: [
    "City Centre",
    "Ancoats",
    "Chorlton",
    "Didsbury",
    "Fallowfield",
    "Hulme",
    "Levenshulme",
    "Moss Side",
    "Old Trafford",
    "Rusholme",
    "Withington",
  ],
  Leicester: [
    "City Centre",
    "Belgrave",
    "Clarendon Park",
    "Evington",
    "Highfields",
    "Knighton",
    "Newfoundpool",
    "Oadby",
    "Spinney Hills",
    "Stoneygate",
  ],
  Sheffield: [
    "City Centre",
    "Crookes",
    "Ecclesall",
    "Hillsborough",
    "Kelham Island",
    "Nether Edge",
    "Walkley",
  ],
  Leeds: [
    "City Centre",
    "Chapel Allerton",
    "Headingley",
    "Holbeck",
    "Horsforth",
    "Hyde Park",
    "Roundhay",
  ],
  Bristol: [
    "City Centre",
    "Bedminster",
    "Clifton",
    "Easton",
    "Fishponds",
    "Horfield",
    "Knowle",
    "St Pauls",
  ],
  Liverpool: [
    "City Centre",
    "Anfield",
    "Aigburth",
    "Kensington",
    "Lark Lane",
    "Toxteth",
    "Wavertree",
    "Woolton",
  ],
  Derby: [
    "City Centre",
    "Allestree",
    "Chaddesden",
    "Littleover",
    "Mickleover",
    "Normanton",
    "Spondon",
  ],
  Coventry: [
    "City Centre",
    "Bell Green",
    "Canley",
    "Cheylesmore",
    "Earlsdon",
    "Stoke",
    "Tile Hill",
  ],
  Bradford: [
    "City Centre",
    "Allerton",
    "Eccleshill",
    "Great Horton",
    "Manningham",
    "Shipley",
    "Thornbury",
  ],
  "Newcastle upon Tyne": [
    "City Centre",
    "Byker",
    "Fenham",
    "Gosforth",
    "Heaton",
    "Jesmond",
    "Walker",
  ],
  Sunderland: [
    "City Centre",
    "Barnes",
    "Fulwell",
    "Hendon",
    "Millfield",
    "Roker",
    "Washington",
  ],
  Hull: [
    "City Centre",
    "Anlaby",
    "Beverley Road",
    "Cottingham",
    "Newland",
    "Stoneferry",
    "West Hull",
  ],
  "Stoke-on-Trent": [
    "City Centre",
    "Burslem",
    "Fenton",
    "Hanley",
    "Longton",
    "Stoke",
    "Tunstall",
  ],
  Wolverhampton: [
    "City Centre",
    "Bilston",
    "Fallings Park",
    "Heath Town",
    "Penn",
    "Tettenhall",
  ],
  Plymouth: [
    "City Centre",
    "Devonport",
    "Efford",
    "Mannamead",
    "Mutley",
    "Peverell",
    "Stonehouse",
  ],
  Southampton: [
    "City Centre",
    "Bevois Valley",
    "Bitterne",
    "Freemantle",
    "Shirley",
    "St Denys",
    "Woolston",
  ],
  Reading: [
    "City Centre",
    "Caversham",
    "Earley",
    "Kings Road",
    "Tilehurst",
    "Whitley",
  ],
  Luton: [
    "Town Centre",
    "Bury Park",
    "Farley",
    "High Town",
    "Leagrave",
    "Stopsley",
  ],
  Northampton: [
    "Town Centre",
    "Abington",
    "Billing",
    "Kingsthorpe",
    "Semilong",
    "Weston Favell",
  ],
  "Milton Keynes": [
    "Central Milton Keynes",
    "Bletchley",
    "Fenny Stratford",
    "Newport Pagnell",
    "Stony Stratford",
    "Wolverton",
  ],
  Swindon: [
    "Town Centre",
    "Gorse Hill",
    "Old Town",
    "Park South",
    "Penhill",
    "Rodbourne",
  ],
  Peterborough: [
    "City Centre",
    "Bretton",
    "Dogsthorpe",
    "Fengate",
    "Millfield",
    "Werrington",
  ],
  Cambridge: [
    "City Centre",
    "Arbury",
    "Cherry Hinton",
    "Chesterton",
    "Mill Road",
    "Trumpington",
  ],
  Oxford: [
    "City Centre",
    "Blackbird Leys",
    "Cowley",
    "Headington",
    "Iffley",
    "Jericho",
  ],
  York: [
    "City Centre",
    "Acomb",
    "Clifton",
    "Fulford",
    "Haxby",
    "Huntington",
  ],
  Gloucester: [
    "City Centre",
    "Barnwood",
    "Longlevens",
    "Matson",
    "Quedgeley",
    "Tuffley",
  ],
  Exeter: [
    "City Centre",
    "Countess Wear",
    "Heavitree",
    "Pinhoe",
    "St Leonards",
    "St Thomas",
  ],
  Cardiff: [
    "City Centre",
    "Canton",
    "Cathays",
    "Grangetown",
    "Llandaff",
    "Roath",
  ],
  Swansea: [
    "City Centre",
    "Brynmill",
    "Gorseinon",
    "Morriston",
    "Sketty",
    "Uplands",
  ],
  Edinburgh: [
    "City Centre",
    "Leith",
    "Morningside",
    "Newington",
    "Portobello",
    "Stockbridge",
  ],
  Glasgow: [
    "City Centre",
    "East End",
    "Finnieston",
    "Maryhill",
    "Partick",
    "Southside",
    "West End",
  ],
  Aberdeen: [
    "City Centre",
    "Bridge of Don",
    "Hazlehead",
    "Old Aberdeen",
    "Rosemount",
    "Torry",
  ],
  Dundee: [
    "City Centre",
    "Broughty Ferry",
    "Coldside",
    "Hilltown",
    "Lochee",
    "West End",
  ],
  Belfast: [
    "City Centre",
    "Antrim Road",
    "Castlereagh",
    "Falls Road",
    "Lisburn Road",
    "Ormeau",
  ],
};

export function getDistrictsForCity(city: string): readonly string[] {
  return UK_DISTRICTS_BY_CITY[city as UkCity] ?? [];
}

export function isValidCity(city: string): city is UkCity {
  return (UK_CITIES as readonly string[]).includes(city);
}

export function isValidDistrict(city: string, district: string): boolean {
  return getDistrictsForCity(city).includes(district);
}
